imxrt-multi: uart parity bit appending fix
phoenix-rtos/phoenix-rtos-devices pull request #278
Opened 2022-08-10 13:56 UTC by gorbanchovie

JIRA: NIL-287

## Description

A fix to appending parity bit to UART data frames for i.MX RT MCUs.
## Motivation and Context

UART configuration for i.MX RT MCUs is different then, for example, for i.MX 6ULL. Parity bit is treated as a part of data bits. So in order to append parity bit to data frame, data length must be incremented.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: i.MX RT1170.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-08-11 07:33 UTC, agkaminski submitted a review, later dismissed
LGTM, cross-checked with the RM

2022-08-11 07:55 UTC, anglov requested changes

2022-08-11 07:55 UTC, anglov commented on multi/imxrt-multi/uart.c
>  		*cflag |= CS8;
It looks invalid.  When you have eg. 7E1  it will set CSIZE to CS8

2022-08-12 08:48 UTC, anglov approved these changes
Solution looks hacky but I think it's valid

2022-08-12 11:44 UTC, agkaminski approved these changes
@anglov  Why hacky? One thing I see (but it's present in the old code too) is that we silently set CS8 if CSIZE != CS7.

2022-08-12 13:36 UTC, merged