storage/imx6ull-flash: Continue reading, when EBADMSG occurs
phoenix-rtos/phoenix-rtos-devices pull request #313
Opened 2022-11-07 14:30 UTC by MaciejPurski

This behavior is expected by the jffs2. It ignores EBADMSG, if we return a requested number of bytes.

JIRA: DTR-347

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-11-08 11:48 UTC, Maxez requested changes

2022-11-08 11:57 UTC, MaciejPurski commented on storage/imx6ull-flash/flashdev.c
> +		return ret;
`_flashmtd_chunkFlips` not only checks the number of bitflips, but also might make a correction on bitflips. It happens, when we receive `flash_uncorrectable` status and check that the actual number of bitflips is smaller than the maximum correctable one.

2022-11-08 11:58 UTC, MaciejPurski commented on storage/imx6ull-flash/flashdev.c
> +			break;
You are right.

2022-11-08 12:16 UTC, Maxez commented on storage/imx6ull-flash/flashdev.c
> +		return ret;
You're right, I've missed the chunk correction part. Thanks for the explanation :)

2022-11-08 13:40 UTC, Maxez approved these changes

2022-11-09 12:02 UTC, nalajcie approved these changes

2022-11-09 14:04 UTC, merged